version: '3.6'
services:
  web:
    restart: always
    image: ikala:latest
    build: .
    env_file:
      - ./env/local.conf
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db-1
    networks:
      - ikala-bridge
    command: "bundle exec rails s -b '0.0.0.0' -p 3000"

  mysql-db-1:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0
    env_file:
      - ./env/local.conf
    volumes:
      - mysql-db-1-data:/var/lib/mysql
    networks:
      - ikala-bridge
    ports:
      - "3306:3306"

networks:
  ikala-bridge:
    driver: bridge

volumes:
  mysql-db-1-data:
