version: '3.6'
services:
  web:
    restart: always
    image: ikala:production
    build: .
    env_file:
      - ./env/production.conf
    depends_on:
      - mysql-db-1
    networks:
      - ikala-bridge
    command: "bundle exec rails s -b '0.0.0.0' -p 3000"

  mysql-db-1:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0
    env_file:
      - ./env/production.conf
    volumes:
      - mysql-db-1-production-data:/var/lib/mysql
    networks:
      - ikala-bridge
  nginx:
    restart: always
    image: nginx:latest
    depends_on:
      - web
      - certbot
    volumes:
      - /data/certbot/www:/var/www/certbot
      - ./nginx_conf/production:/etc/nginx/conf.d
      - /data/certbot/letsencrypt:/etc/letsencrypt
    networks:
      - ikala-bridge
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    restart: always
    image: certbot/certbot:v1.8.0
    volumes:
      - /data/certbot/letsencrypt:/etc/letsencrypt
    networks:
      - ikala-bridge
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --force-renewal; sleep 12h & wait $${!}; done;'"

networks:
  ikala-bridge:
    driver: bridge

volumes:
  mysql-db-1-production-data:
